# LinAlg/Makefile

NAME := LinAlg
OBJS := sgrid_$(NAME).o SparseVector_utils.o ReadMatrixFrom_Fx.o \
	lapack_interface.o umfpack_di_interface.o umfpack_dl_interface.o \
	SuiteSparseQR_C_interface.o

include $(TOP)/Makefile.subdirs

