# numerics/Makefile

NAME := numerics

OBJS := sgrid_$(NAME).o newton1d_brak.o rt_brak.o rtbrent_brak.o lu.o \
	newton_linesearch.o minbrent_brak.o \
	NumericUtils_shims.o WT_Random.o

include $(TOP)/Makefile.subdirs
