# ModeComputer/Makefile

NAME := ModeComputer
OBJS := sgrid_$(NAME).o ModeComputer.o SpinWeightedSphericalHarmonics.o

include $(TOP)/Makefile.subdirs

#ModeComputerKS.c: ModeComputerKS.m
#	math < ModeComputerKS.m > /dev/null

