# NumericUtils/Makefile

NAME := NumericUtils
OBJS := sgrid_$(NAME).o integral.o integral3D.o newton_lnsrch.o nrutil.o f_to_minimize.o fd_jacobian.o ludcmp.o lubksb.o lnsrch_double.o attenuation.o rkck.o rkqs.o odeintegrate.o brent.o integrals_1Dgrid.o powell.o linmin.o mnbrak.o zbrac.o zbrent.o WT_newton.o

include $(TOP)/Makefile.subdirs

