# TestID/Makefile

NAME := TestID
OBJS := sgrid_$(NAME).o TestID.o TestID_1dGaugeWave.o TestID_1dLinearWave.o \
	TestID_RandomNoise.o

include $(TOP)/Makefile.subdirs

#TestIDKS.c: TestIDKS.m
#	math < TestIDKS.m > /dev/null

