# GridIterators/Makefile

NAME := GridIterators

OBJS := sgrid_$(NAME).o Newton.o bicgstab.o utility.o wrappers_for_templates.o wrappers_for_LAPACK.o wrappers_for_UMFPACK.o WTsolver.o

include $(TOP)/Makefile.subdirs
