# Spectral/Makefile

NAME := Spectral
OBJS := sgrid_$(NAME).o explicit_Cheb_trafos.o derivs.o diffmatrices.o matrices.o explicit_Four_trafos.o filters.o finite_differences.o

include $(TOP)/Makefile.subdirs

