# checkpoint/Makefile

NAME := checkpoint

OBJS := sgrid_$(NAME).o checkpoint.o checkpoint_read.o checkpoint_write.o \
        checkpoint_wolfio.o parameterio.o read_other_checkpoints.o

include $(TOP)/Makefile.subdirs
