# PN_CircularOrbit_GWs/Makefile

NAME := PN_CircularOrbit_GWs
OBJS := sgrid_$(NAME).o PN_CircularOrbit_GWs.o xodeint.o compute_graw_wave.o

include $(TOP)/Makefile.subdirs

#PN_CircularOrbit_GWsKS.c: PN_CircularOrbit_GWsKS.m
#	math < PN_CircularOrbit_GWsKS.m > /dev/null

