# PN_CircularOrbit_GWs/Makefile

NAME := PN_CircularOrbit_GWs
OBJS := sgrid_$(NAME).o PN_CircularOrbit_GWs.o PN_CircOrbit.o compute_GWs.o minimize_PN-NR_diff.o

include $(TOP)/Makefile.subdirs

#PN_CircularOrbit_GWsKS.c: PN_CircularOrbit_GWsKS.m
#	math < PN_CircularOrbit_GWsKS.m > /dev/null

