# DV_CircSchwSource/Makefile

NAME := DV_CircSchwSource
OBJS := sgrid_$(NAME).o DV_CircSchwSource.o Constants.o Schwarzschild.o \
        Source.o THZ.o Singular.o Window_DONUT.o

include $(TOP)/Makefile.subdirs

